name: Deploy

on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo "Render hace auto-deploy al hacer push. Este workflow no es necesario."